version: "2"
services:
  postgres:
    container_name: photos_db
    build:
      context: ./docker/postgres
    env_file:
      - ./docker/postgres.env
    ports:
      - "5432:5432"
  django:
    container_name: photos_app
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file:
      - ./docker/django.env
      - ./docker/postgres.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
